### ISSUE TITLE
Errors when viewing demo in Safari 6.2.4

### ISSUE THREAD

**Issue by twelvelabs** [okor/justice#19]
I went to http://okor.github.io/justice/ in Safari and did not see the expected metric bar. The following errors were in the console:

```
[Error] TypeError: undefined is not an object (evaluating 'window.performance.timing')
	(anonymous function) (justice.min.js, line 1)
	global code (justice.min.js, line 1)
[Error] TypeError: undefined is not an object (evaluating 'Justice.init')
	global code (justice, line 93)
```

OS X 10.8.5 
Safari 6.2.4

If browsers don't support `window.performance` Justice should fail gracefully.

**Comment by okor** [comment]
Hmm, I thought I had that covered. Must have regressed. I'll fix that and see if I can get this repo wired up to some kind of CI with multi browser checks.

**Comment by okor** [comment]
It's fixed.
