### ISSUE TITLE
Background Changes

### ISSUE THREAD

**Issue by TheoBearman** [okor/justice#26]
Might be nice to be able to change some of the looks of the toolbar. Background colour and text colour changes for example?

Thanks!

**Comment by okor** [comment]
I agree it would be cool. I was thinking of doing something like this: http://viget.com/extend/sharing-data-between-sass-and-javascript-with-json Since colors need to be in JS and SCSS. This way anyone could create a custom build.

**Comment by TheoBearman** [comment]
@okor Looks good!

**Comment by okor** [comment]
Consolidating similar issues here: https://github.com/okor/justice/issues/28
