### ISSUE TITLE
Question: Shift in trackFPS

### ISSUE THREAD

**Issue by kennyt** [okor/justice#34]
does
```
dataFpsHistory.shift()
```
have to reindex the 400 length array every single time it gets called? or is this not a problem?

**Comment by kennyt** [comment]
For example, this: http://stackoverflow.com/questions/6501160/why-is-pop-faster-than-shift says that shift does have to reindex everytime.

But I've also read somewhere that v8 has optimized shift in smaller arrays, so I'm unsure

**Comment by okor** [comment]
This is also in the realm of micro-optimizations and not generally worth taking the time to investigate. But again, it's in a fast loop so hey why not.

There are several tests linked from that thread and pop is anywhere from 0.5% to 50% faster depending on how they wrote the test. I spoke with a coworker about these kinds of tests and talked a bit about how JIT compilers optimize code. The tl;dr is that "it depends". I'm not sure if it would make a reasonable difference in the Justice code .... but if you are curious you could create a test in the real Justice code (not isolated snipped on jsperf) and measure the difference in execution time using the two different functions. Then you can tell me what's faster : )

Keep in mind that different Javascript JIT compilers will very likely compile differently. So something may be very fast in Chrome but slow in FF, or whatever. So to answer the question fully, you'd need to create the test case like I outlined and then benchmark in all relevant browsers (pretty much anything with the 'performance' interface). 

Going to close this issue but feel free to add any findings here and will reopen if the data indicates we could get some significant performance increase.
