### ISSUE TITLE
Share color variables between SCSS and JS

### ISSUE THREAD

**Issue by okor** [okor/justice#7]
DRY and should make theming very easy.

**Comment by necolas** [comment]
You might want to use inline styles and JS variables. Easier to theme for consumers too.

**Comment by okor** [comment]
I'm definitely open to this idea of inline styles. I think I would probably approach this as "overrides" and default to the static compiled theme.

But I still think it would be cool to use a YAML file or similar to share default colors between Sass and JS during compilation.

**Comment by okor** [comment]
@necolas Done in https://github.com/okor/justice/commits/themes (requires editing src/theme.json). Not entirely happy with solution it's in a branch until I can decide what to do with it. Maybe check out that branch and see what you think. Feel free to clean up any glaring ugliness in a PR.

**Comment by okor** [comment]
Consolidating similar issues here: https://github.com/okor/justice/issues/28
